import type { Context } from "hono";
import { verifyUserKey } from "./auth.js";
import { extractBearerToken } from "./opik.js";
import { TdaiClient } from "./tdai/client.js";
import { deriveTdaiIdentity } from "./tdai/identity.js";
import { isExtractionAllowed } from "./extraction-gate.js";
import { triggerSkillExtractIfReady } from "./skill/handler-glue.js";
import { getMetadataClient } from "./meta/client.js";
import { fetchAssetCapabilities } from "./tdai/capabilities.js";
import {
  getSessionStore,
  handleClaudeCodeSessionInit,
  type PresetIdentity,
  type SessionInfo,
} from "./session/index.js";
import { restoreSessionSpaceId } from "./session/restore-space-id.js";
import type { TdaiIdentity } from "./tdai/types.js";
import type { ProxyConfig } from "./types.js";

type JsonRecord = Record<string, unknown>;

const SKIP_REQUEST_HEADERS = new Set([
  "authorization",
  "connection",
  "content-length",
  "host",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
  "x-api-key",
  "x-team-id",
  "x-agent-id",
  "x-task-id",
  "x-tdai-team-id",
  "x-tdai-agent-id",
  "x-tdai-task-id",
]);

const SKIP_RESPONSE_HEADERS = new Set([
  "connection",
  "content-encoding",
  "content-length",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
]);

/**
 * Native Codex Responses handler.
 *
 * Codex cannot render the Claude/CodeBuddy selection forms. Its profile is
 * generated by Memory Hub with a Team/Agent/Task header triple instead. The
 * triple is still validated and registered through the normal session store,
 * so loadout, asset ACL, prewarm, knowledge, L0-L3 memory and participation
 * accounting are identical to the existing clients.
 */
export async function handleCodexResponses(
  c: Context,
  config: ProxyConfig,
): Promise<Response> {
  const spaceId = c.req.param("spaceId") ?? "";
  const userKey = extractBearerToken(c.req.header("authorization") ?? "");
  const verified = await verifyUserKey(userKey, spaceId);
  if (verified.rejected) {
    return c.json({
      error: {
        message: verified.rejectReason ?? "invalid user_key",
        type: "authentication_error",
      },
    }, 401);
  }

  let body: JsonRecord;
  try {
    const parsed = await c.req.json<unknown>();
    if (!isRecord(parsed)) throw new Error("body must be an object");
    body = parsed;
  } catch {
    return codexError(c, 400, "invalid JSON request body", "invalid_request_error");
  }

  const sessionId = resolveSessionId(c, body);
  const selection = readSelection(c);
  const requiresSession = config.sessionInit?.enabled === true;
  if (requiresSession && !hasCompleteSelection(selection)) {
    return codexError(
      c,
      400,
      "Codex is not configured with a Team, Agent, and Task. Generate a Codex profile from Memory Hub before starting this session.",
      "invalid_request_error",
      "codex_identity_required",
    );
  }

  let upstreamBody = body;
  let sessionInfo: SessionInfo | null | undefined;
  let agentDetail: import("./session/types.js").AgentDetail | null | undefined;
  let taskDetail: import("./session/types.js").TaskDetail | null | undefined;
  let assetCapabilities: import("./injection/types.js").AssetCapabilityFlags | undefined;

  if (requiresSession) {
    try {
      // Initializing the pipeline also activates the shared storage backend
      // before `getOrRecover` probes the persisted Codex binding.
      if (config.injection?.enabled) {
        const { getInjectionPipeline } = await import("./injection/index.js");
        getInjectionPipeline(config);
      }

      const store = getSessionStore();
      const metadataClient = getMetadataClient(config.coreSkill, spaceId, userKey);
      const sessionMessages = responseInputToSessionMessages(body.input);
      const storeIdentity = {
        userId: verified.userId || "anonymous",
        agentSource: "codex",
        sessionId,
        spaceId,
      };
      await store.getOrRecover(`codex:${sessionId}`, storeIdentity, {
        metadataClient,
        messages: sessionMessages,
      });

      const sessionConfig = {
        ...config.sessionInit,
        headerAutoSelect: {
          ...(config.sessionInit.headerAutoSelect ?? {
            enabled: true,
            teamHeader: "x-team-id",
            agentHeader: "x-agent-id",
            taskHeader: "x-task-id",
            onMismatch: "bypass" as const,
          }),
          enabled: true,
          // Codex has no fake form fallback. An invalid Hub-generated profile
          // must be rejected instead of reaching an upstream model unbound.
          onMismatch: "bypass" as const,
        },
      };
      const initResult = await handleClaudeCodeSessionInit(
        sessionId,
        verified.userId || null,
        sessionMessages,
        sessionConfig,
        store,
        {
          stream: body.stream === true,
          modelId: typeof body.model === "string" ? body.model : "codex",
          // Return the context block to this handler. Responses keeps system
          // instructions in `input` developer items, not an Anthropic field.
          protocol: "anthropic",
          agentSource: "codex",
        },
        metadataClient,
        userKey,
        spaceId,
        selection,
      );

      if (initResult.intercepted || initResult.bypassed || !initResult.sessionInfo) {
        return codexError(
          c,
          403,
          "The selected Codex Team, Agent, or Task is unavailable to this user. Regenerate the profile from Memory Hub.",
          "invalid_request_error",
          "codex_identity_invalid",
        );
      }

      sessionInfo = initResult.sessionInfo;
      agentDetail = initResult.agentDetail;
      taskDetail = initResult.taskDetail;
      restoreSessionSpaceId(sessionInfo as unknown as Record<string, unknown>, spaceId);
      if (initResult.systemAppend) {
        upstreamBody = appendDeveloperContext(upstreamBody, initResult.systemAppend);
      }

      try {
        assetCapabilities = await fetchAssetCapabilities({
          endpoint: config.tdai.endpoint,
          apiKey: config.tdai.apiKey,
          serviceId: config.tdai.serviceId,
          serviceIdOverride: spaceId,
          userId: sessionInfo.user_id,
          userKey: userKey || null,
          timeoutMs: config.tdai.memory.timeoutMs,
        });
      } catch (error) {
        console.warn(`[codex] asset capability lookup failed: ${messageOf(error)}`);
      }

      if (
        initResult.justRegistered &&
        config.injection?.enabled &&
        (config.injection.injectors?.length ?? 0) > 0
      ) {
        const { prewarmFromConfig } = await import("./injection/index.js");
        await prewarmFromConfig(config, {
          keyId: sessionId,
          userId: verified.userId || "anonymous",
          agentSource: "codex",
          spaceId,
          sessionInfo,
          agentDetail: agentDetail ?? null,
          taskDetail: taskDetail ?? null,
          assetCapabilities,
          callerUserKey: userKey || undefined,
        });
      }

      if (config.injection?.enabled && (config.injection.injectors?.length ?? 0) > 0) {
        const { getInjectionPipeline } = await import("./injection/index.js");
        upstreamBody = await getInjectionPipeline(config).process(upstreamBody, {
          protocol: "responses",
          traceId: `codex:${sessionId}:${crypto.randomUUID()}`,
          keyId: verified.userId || "anonymous",
          modelId: typeof body.model === "string" ? body.model : "codex",
          stream: body.stream === true,
          agentSource: "codex",
          userId: verified.userId || "anonymous",
          spaceId,
          sessionKey: sessionId,
          turnSeq: countUserTurns(responseInputToSessionMessages(upstreamBody.input)),
          requestPath: c.req.path,
          custom: {
            session: sessionInfo,
            assetCapabilities,
            userKey: userKey || undefined,
          },
        });
      }
    } catch (error) {
      console.error(`[codex] session initialization failed: ${messageOf(error)}`);
      return codexError(
        c,
        502,
        "Codex memory session initialization failed. The model request was not forwarded without its selected identity.",
        "server_error",
        "codex_session_initialization_failed",
      );
    }
  }

  const agentUpstream = config.upstream.agents?.codex;
  const upstreamBaseUrl = agentUpstream?.url ?? config.upstream.url;
  const upstreamApiKey = agentUpstream ? (agentUpstream.apiKey ?? "") : config.upstream.apiKey;
  if (!upstreamBaseUrl) {
    return codexError(c, 502, "Codex upstream is not configured", "server_error");
  }

  const userQuery = extractLatestUserText(body.input);
  const tdaiClient = assetCapabilities?.chat_memory === false ? null : createTdaiClient(config, spaceId);
  const tdaiIdentity = deriveTdaiIdentity({
    sessionInfo: sessionInfo as Record<string, unknown> | null | undefined,
    userId: verified.userId || null,
    sessionKey: sessionId,
    userKey: userKey || null,
  });
  const sessionMessages = responseInputToSessionMessages(body.input);

  let upstreamResponse: Response;
  try {
    const options: RequestInit = {
      method: "POST",
      headers: buildUpstreamHeaders(c, upstreamApiKey),
      body: JSON.stringify(upstreamBody),
    };
    if (config.server.forwardTimeoutMs && config.server.forwardTimeoutMs > 0) {
      options.signal = AbortSignal.timeout(config.server.forwardTimeoutMs);
    }
    upstreamResponse = await fetch(resolveResponsesUrl(upstreamBaseUrl), options);
  } catch {
    return codexError(c, 502, "upstream Responses API request failed", "server_error");
  }

  const responseHeaders = copyResponseHeaders(upstreamResponse.headers);
  if (body.stream === true && upstreamResponse.body) {
    return new Response(
      upstreamResponse.body.pipeThrough(createCaptureTap({
        client: tdaiClient,
        identity: tdaiIdentity,
        userQuery,
        sessionInfo,
        sessionId,
        sessionMessages,
        assetCapabilities,
        config,
        captureEnabled: upstreamResponse.ok,
      })),
      { status: upstreamResponse.status, headers: responseHeaders },
    );
  }

  const responseText = await upstreamResponse.text();
  if (upstreamResponse.ok) {
    void captureTurn({
      client: tdaiClient,
      identity: tdaiIdentity,
      userQuery,
      assistantText: extractResponseText(responseText),
      sessionInfo,
      sessionId,
      sessionMessages,
      assetCapabilities,
      config,
      hasToolCalls: responseHasToolCalls(responseText),
    });
  }
  return new Response(responseText, { status: upstreamResponse.status, headers: responseHeaders });
}

function createTdaiClient(config: ProxyConfig, spaceId: string): TdaiClient | null {
  if (!config.tdai.enabled || !config.tdai.memory.enabled || !config.tdai.endpoint) return null;
  return new TdaiClient({
    enabled: true,
    endpoint: config.tdai.endpoint,
    apiKey: config.tdai.apiKey,
    serviceId: spaceId || config.tdai.serviceId,
    writeL0: config.tdai.memory.writeL0,
    recallL1: config.tdai.memory.recallL1,
    injectL2L3: config.tdai.memory.injectL2L3,
    l1Limit: config.tdai.memory.l1Limit,
    l2Limit: config.tdai.memory.l2Limit,
    timeoutMs: config.tdai.memory.timeoutMs,
  });
}

function readSelection(c: Context): PresetIdentity {
  return {
    teamId: readHeader(c, "x-tdai-team-id", "x-team-id"),
    agentId: readHeader(c, "x-tdai-agent-id", "x-agent-id"),
    taskId: readHeader(c, "x-tdai-task-id", "x-task-id"),
  };
}

function readHeader(c: Context, preferred: string, fallback: string): string | undefined {
  const value = c.req.header(preferred)?.trim() || c.req.header(fallback)?.trim();
  return value || undefined;
}

function hasCompleteSelection(selection: PresetIdentity): boolean {
  return Boolean(selection.teamId && selection.agentId && selection.taskId);
}

function resolveSessionId(c: Context, body: JsonRecord): string {
  const clientMetadata = getRecord(body.client_metadata);
  const sessionId = [
    c.req.header("session-id"),
    c.req.header("x-session-id"),
    c.req.header("x-conversation-id"),
    getString(clientMetadata?.session_id),
    getString(body.previous_response_id),
    getString(body.prompt_cache_key),
  ].find((value): value is string => typeof value === "string" && value.trim().length > 0);
  if (sessionId) return sessionId.trim();

  const turnMetadata = c.req.header("x-codex-turn-metadata");
  if (turnMetadata) {
    try {
      const parsed = JSON.parse(turnMetadata) as JsonRecord;
      const metadataSessionId = getString(parsed.session_id);
      if (metadataSessionId) return metadataSessionId;
    } catch {
      // Vendor metadata is optional and must not reject an otherwise valid request.
    }
  }
  return `codex-${crypto.randomUUID()}`;
}

function responseInputToSessionMessages(input: unknown): JsonRecord[] {
  const items = Array.isArray(input) ? input : [input];
  return items.flatMap((item) => {
    const record = getRecord(item);
    const role = getString(record?.role);
    if (!record || !role) return [];
    return [{
      ...record,
      role: role === "developer" ? "system" : role,
    }];
  });
}

function appendDeveloperContext(body: JsonRecord, context: string): JsonRecord {
  const original = Array.isArray(body.input)
    ? body.input
    : body.input == null
      ? []
      : [{ type: "message", role: "user", content: [{ type: "input_text", text: String(body.input) }] }];
  const developerInput = {
    type: "message",
    role: "developer",
    content: [{ type: "input_text", text: context }],
  };
  const insertAt = original.findIndex((item) => getRecord(item)?.role === "user");
  const position = insertAt === -1 ? original.length : insertAt;
  return {
    ...body,
    input: [...original.slice(0, position), developerInput, ...original.slice(position)],
  };
}

function extractLatestUserText(input: unknown): string {
  const items = Array.isArray(input) ? input : [input];
  for (let index = items.length - 1; index >= 0; index -= 1) {
    const item = getRecord(items[index]);
    if (item?.role !== "user") continue;
    const text = contentToText(item.content).trim();
    if (text) return text.slice(0, 2048);
  }
  return typeof input === "string" ? input.trim().slice(0, 2048) : "";
}

function countUserTurns(messages: JsonRecord[]): number {
  return messages.filter((message) => message.role === "user").length;
}

function buildUpstreamHeaders(c: Context, apiKey: string): Headers {
  const headers = new Headers();
  for (const [key, value] of c.req.raw.headers.entries()) {
    if (!SKIP_REQUEST_HEADERS.has(key.toLowerCase())) headers.set(key, value);
  }
  headers.set("content-type", "application/json");
  if (apiKey) headers.set("authorization", `Bearer ${apiKey}`);
  return headers;
}

function resolveResponsesUrl(baseUrl: string): string {
  const normalized = baseUrl.replace(/\/+$/, "");
  return normalized.endsWith("/responses") ? normalized : `${normalized}/responses`;
}

function copyResponseHeaders(source: Headers): Headers {
  const headers = new Headers();
  for (const [key, value] of source.entries()) {
    if (!SKIP_RESPONSE_HEADERS.has(key.toLowerCase())) headers.set(key, value);
  }
  return headers;
}

interface CaptureContext {
  client: TdaiClient | null;
  identity: TdaiIdentity | null;
  userQuery: string;
  sessionInfo: SessionInfo | null | undefined;
  sessionId: string;
  sessionMessages: JsonRecord[];
  assetCapabilities: import("./injection/types.js").AssetCapabilityFlags | undefined;
  config: ProxyConfig;
  captureEnabled?: boolean;
}

function createCaptureTap(context: CaptureContext): TransformStream<Uint8Array, Uint8Array> {
  const decoder = new TextDecoder();
  let buffer = "";
  let deltas = "";
  let completed = "";
  let hasToolCalls = false;

  const observe = (chunk: string) => {
    buffer += chunk;
    const events = buffer.split("\n\n");
    buffer = events.pop() ?? "";
    for (const event of events) {
      const eventName = event.match(/^event:\s*(.+)$/m)?.[1]?.trim();
      const data = event
        .split("\n")
        .filter((line) => line.startsWith("data:"))
        .map((line) => line.slice(5).trim())
        .join("\n");
      if (!data || data === "[DONE]") continue;
      try {
        const payload = JSON.parse(data) as JsonRecord;
        if (eventName === "response.output_text.delta") {
          const delta = getString(payload.delta);
          if (delta) deltas += delta;
        }
        if (eventName?.includes("function_call") || eventName?.includes("tool_call")) {
          hasToolCalls = true;
        }
        if (eventName === "response.completed") {
          const response = getRecord(payload.response);
          const text = response ? extractResponseText(JSON.stringify(response)) : "";
          if (text) completed = text;
          if (response && responseHasToolCalls(JSON.stringify(response))) hasToolCalls = true;
        }
      } catch {
        // The event is still relayed byte-for-byte when its data is malformed.
      }
    }
  };

  return new TransformStream<Uint8Array, Uint8Array>({
    transform(chunk, controller) {
      controller.enqueue(chunk);
      observe(decoder.decode(chunk, { stream: true }));
    },
    flush() {
      observe(decoder.decode());
      if (context.captureEnabled !== false) {
        void captureTurn({
          ...context,
          assistantText: completed || deltas,
          hasToolCalls,
        });
      }
    },
  });
}

async function captureTurn(context: CaptureContext & { assistantText: string; hasToolCalls: boolean }): Promise<void> {
  if (!context.client || !context.identity || !context.userQuery) return;
  try {
    await context.client.addConversation(context.identity, [
      { role: "user", content: context.userQuery },
      ...(context.assistantText.trim() ? [{ role: "assistant" as const, content: context.assistantText.trim() }] : []),
    ]);
  } catch {
    // Memory persistence is intentionally fail-open for model traffic.
  }

  if (
    !context.hasToolCalls &&
    context.sessionInfo &&
    isExtractionAllowed(context.config, "skill")
  ) {
    await triggerSkillExtractIfReady({
      config: context.config,
      sessionKey: context.sessionId,
      agentSource: "codex",
      sessionInfo: context.sessionInfo as unknown as Record<string, unknown>,
      inputMessages: context.sessionMessages,
      assistantMessage: { role: "assistant", content: context.assistantText },
      // Codex response items are normalized as OpenAI-style text messages for
      // the existing round extractor; this does not alter the wire protocol.
      protocol: "openai",
      assetCapabilities: context.assetCapabilities,
    });
  }
}

function extractResponseText(raw: string): string {
  try {
    const response = JSON.parse(raw) as JsonRecord;
    const outputText = getString(response.output_text);
    if (outputText) return outputText;
    const output = Array.isArray(response.output) ? response.output : [];
    return output
      .map((item) => contentToText(getRecord(item)?.content))
      .filter(Boolean)
      .join("\n")
      .trim();
  } catch {
    return "";
  }
}

function responseHasToolCalls(raw: string): boolean {
  try {
    const response = JSON.parse(raw) as JsonRecord;
    const output = Array.isArray(response.output) ? response.output : [];
    return output.some((item) => {
      const type = getString(getRecord(item)?.type) ?? "";
      return type.includes("function_call") || type.includes("tool_call") || type.includes("computer_call");
    });
  } catch {
    return false;
  }
}

function contentToText(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .map((part) => {
      const record = getRecord(part);
      return getString(record?.text) ?? getString(record?.content) ?? "";
    })
    .join("\n");
}

function codexError(
  c: Context,
  status: 400 | 403 | 502,
  message: string,
  type: "invalid_request_error" | "server_error",
  code?: string,
): Response {
  return c.json({ error: { message, type, ...(code ? { code } : {}) } }, status);
}

function isRecord(value: unknown): value is JsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function getRecord(value: unknown): JsonRecord | undefined {
  return isRecord(value) ? value : undefined;
}

function getString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
