/**
 * 会话锁自动生成（评审意见 7 / 开放题五 autoConversationId）。
 *
 * 对于没有自带稳定会话 ID 的客户端（Hermes / OpenClaw / DSH 等），服务端基于
 * `clientId（API key 派生 keyId）+ 首次连接时间` 生成不可预测的会话锁，
 * 避免不同客户端上报相同 sessionKey 导致会话锁碰撞、隔离失效。
 *
 * 单节点实现：进程内 Map + TTL（默认 30 分钟）；多节点需换 Redis。
 * 显式上报的会话 ID 始终优先，本机制只在缺失时触发（完全向后兼容）。
 */
import { randomUUID, createHash } from "node:crypto";

export interface AutoConversationIdConfig {
  enabled?: boolean;
  ttlMinutes?: number;
  strategy?: "per-key" | "per-key-msg";
}

interface ActiveSession {
  sid: string;
  lastSeen: number;
}

interface MsgSession {
  sid: string;
  fingerprint: string;
  lastSeen: number;
}

const ACTIVE = new Map<string, ActiveSession>();
const ACTIVE_MSG = new Map<string, MsgSession[]>();
const MAX_ENTRIES = 2048;
const MAX_WINDOWS_PER_KEY = 8;

// ── 可注入时钟（测试用）─────────────────────────────────────────────────
let nowFn: () => number = () => Date.now();

/** 测试专用：替换当前时间源（vitest 里配合 __resetAutoSessionForTests 使用）。 */
export function __setAutoSessionNow(fn: () => number): void {
  nowFn = fn;
}

/** 测试专用：清空进程内会话表，避免用例间状态串扰。 */
export function __resetAutoSessionForTests(): void {
  ACTIVE.clear();
  ACTIVE_MSG.clear();
}

/** 从首条用户消息文本生成稳定的会话指纹（sha256 前 16 hex）。 */
export function messageFingerprint(text: string): string {
  return createHash("sha256").update(text ?? "").digest("hex").slice(0, 16);
}

/**
 * 解析会话 ID：显式 ID 优先；缺失且开启 auto 时按 keyId 生成/续接。
 * 返回 { sessionId, autoGenerated }；autoGenerated=true 表示服务端生成。
 */
export function resolveOrCreateSessionId(
  existing: string | null,
  keyId: string,
  cfg: AutoConversationIdConfig | undefined,
  msgFingerprint?: string,
): { sessionId: string; autoGenerated: boolean; reused?: boolean } {
  if (existing && existing.length > 0) {
    return { sessionId: existing, autoGenerated: false };
  }
  if (!cfg?.enabled) {
    return { sessionId: "", autoGenerated: false };
  }
  const ttlMs = (cfg.ttlMinutes ?? 30) * 60_000;
  const now = nowFn();
  const strategy = cfg.strategy ?? "per-key";

  // per-key-msg：同一 key 下按"首条用户消息指纹"区分多个窗口（支持多窗口并行）。
  if (strategy === "per-key-msg" && msgFingerprint) {
    const list = ACTIVE_MSG.get(keyId);
    if (list) {
      const hit = list.find(
        (s) => s.fingerprint === msgFingerprint && now - s.lastSeen < ttlMs,
      );
      if (hit) {
        hit.lastSeen = now;
        return { sessionId: hit.sid, autoGenerated: true, reused: true };
      }
    }
    const sid = `auto-${keyId}-${randomUUID()}`;
    const entry: MsgSession = { sid, fingerprint: msgFingerprint, lastSeen: now };
    const next = list
      ? [entry, ...list.filter((s) => now - s.lastSeen < ttlMs)]
      : [entry];
    ACTIVE_MSG.set(keyId, next.slice(0, MAX_WINDOWS_PER_KEY));
    return { sessionId: sid, autoGenerated: true, reused: false };
  }

  const hit = ACTIVE.get(keyId);
  if (hit && now - hit.lastSeen < ttlMs) {
    hit.lastSeen = now;
    return { sessionId: hit.sid, autoGenerated: true, reused: true };
  }
  const sid = `auto-${keyId}-${randomUUID()}`;
  ACTIVE.set(keyId, { sid, lastSeen: now });
  if (ACTIVE.size > MAX_ENTRIES) {
    for (const [k, v] of ACTIVE) {
      if (now - v.lastSeen > ttlMs) ACTIVE.delete(k);
    }
  }
  return { sessionId: sid, autoGenerated: true, reused: false };
}
