/**
 * 会话锁自动生成（评审意见 7 / 开放题五 autoConversationId）。
 *
 * 对于没有自带稳定会话 ID 的客户端（Hermes / OpenClaw / DSH 等），服务端基于
 * `clientId（API key 派生 keyId）+ 首次连接时间` 生成不可预测的会话锁，
 * 避免不同客户端上报相同 sessionKey 导致会话锁碰撞、隔离失效。
 *
 * 单节点实现：进程内 Map + TTL（默认 30 分钟）；多节点需换 Redis。
 * 显式上报的会话 ID 始终优先，本机制只在缺失时触发（完全向后兼容）。
 */
import { randomUUID } from "node:crypto";

export interface AutoConversationIdConfig {
  enabled?: boolean;
  ttlMinutes?: number;
  strategy?: "per-key" | "per-key-msg";
}

interface ActiveSession {
  sid: string;
  lastSeen: number;
}

const ACTIVE = new Map<string, ActiveSession>();
const MAX_ENTRIES = 2048;

/**
 * 解析会话 ID：显式 ID 优先；缺失且开启 auto 时按 keyId 生成/续接。
 * 返回 { sessionId, autoGenerated }；autoGenerated=true 表示服务端生成。
 */
export function resolveOrCreateSessionId(
  existing: string | null,
  keyId: string,
  cfg: AutoConversationIdConfig | undefined,
): { sessionId: string; autoGenerated: boolean } {
  if (existing && existing.length > 0) {
    return { sessionId: existing, autoGenerated: false };
  }
  if (!cfg?.enabled) {
    return { sessionId: "", autoGenerated: false };
  }
  const ttlMs = (cfg.ttlMinutes ?? 30) * 60_000;
  const now = Date.now();
  const hit = ACTIVE.get(keyId);
  if (hit && now - hit.lastSeen < ttlMs) {
    hit.lastSeen = now;
    return { sessionId: hit.sid, autoGenerated: true };
  }
  const sid = `auto-${keyId}-${randomUUID()}`;
  ACTIVE.set(keyId, { sid, lastSeen: now });
  if (ACTIVE.size > MAX_ENTRIES) {
    for (const [k, v] of ACTIVE) {
      if (now - v.lastSeen > ttlMs) ACTIVE.delete(k);
    }
  }
  return { sessionId: sid, autoGenerated: true };
}
