/**
 * Session key resolution & conversation freshness check.
 *
 * Shared between handler.ts and anthropicHandler.ts.
 */
import type { Context } from "hono";
import type { ProxyConfig } from "../types.js";
import { resolveOrCreateSessionId, messageFingerprint } from "./auto-session.js";

/** Extract conversation ID from request headers. Returns null if no valid ID found. */
export function resolveConversationId(c: Context): string | null {
  const id =
    c.req.header("x-conversation-id") ??
    c.req.header("x-session-id") ??
    c.req.header("x-claude-code-session-id") ?? // Claude Code CLI sends this
    c.req.header("x-deepseek-harness-session-id") ?? // dsh (deepseek-harness) CLI/web sends this
    c.req.header("x-chat-id") ??
    c.req.header("x-thread-id") ??
    null;
  return id && id.length > 0 ? id : null;
}

/**
 * 独立提取 thread 维度（评审意见 1：task 之下加 thread 层）。
 * thread 与 conversation 是两层：conversation 决定对话连续性，
 * thread 决定主题分组（记忆检索先收敛 thread）。
 * 仅显式传 `x-thread-id` 时生效；未传返回 null（保持单层行为）。
 */
export function resolveThreadId(c: Context): string | null {
  const id = c.req.header("x-thread-id") ?? null;
  return id && id.length > 0 ? id : null;
}

/** 统一入口：显式会话 ID 优先，缺失时按配置自动生成（autoConversationId）。 */
export function resolveEffectiveConversationId(
  c: Context,
  keyId: string,
  config: ProxyConfig,
  msgFingerprint?: string,
): { conversationId: string | null; autoGenerated: boolean; reused?: boolean; threadId: string | null } {
  const raw = resolveConversationId(c);
  const auto = resolveOrCreateSessionId(
    raw,
    keyId,
    config.sessionInit?.autoConversationId,
    msgFingerprint,
  );
  return {
    conversationId: auto.sessionId || raw,
    autoGenerated: auto.autoGenerated,
    reused: auto.reused,
    threadId: resolveThreadId(c),
  };
}

/**
 * 从请求消息列表提取首条用户消息文本并生成指纹，供 per-key-msg 策略使用。
 * 兼容 Anthropic（content 为 string/block 数组）、OpenAI Chat（content 为 string）
 * 与 Responses（input 项 content 为 block 数组）。
 */
export function firstUserMessageFingerprint(messages: unknown): string | undefined {
  if (!Array.isArray(messages)) return undefined;
  for (const m of messages) {
    if (!m || typeof m !== "object") continue;
    const role = (m as { role?: unknown }).role;
    if (role !== "user") continue;
    const content = (m as { content?: unknown }).content;
    let text = "";
    if (typeof content === "string") text = content;
    else if (Array.isArray(content)) {
      text = content
        .map((b) => {
          if (typeof b === "string") return b;
          if (b && typeof b === "object") {
            const t = (b as { text?: unknown }).text;
            if (typeof t === "string") return t;
          }
          return "";
        })
        .join(" ");
    }
    if (!text.trim()) continue;
    return messageFingerprint(text.trim().slice(0, 512));
  }
  return undefined;
}

/**
 * 生命周期隔离（评审意见 6）：命名空间命中 archive 规则时视为已归档，
 * 会话不恢复（重新走 Session Init），旧记忆不进入活跃检索。
 */
export function isNamespaceArchived(
  config: ProxyConfig,
  ids: { spaceId?: string; teamId?: string; agentId?: string },
): boolean {
  const rules = config.storage?.archiveNamespaces;
  if (!Array.isArray(rules) || rules.length === 0) return false;
  return rules.some((r) => {
    if (r.spaceId && r.spaceId !== ids.spaceId) return false;
    if (r.teamId && r.teamId !== ids.teamId) return false;
    if (r.agentId && r.agentId !== ids.agentId) return false;
    return true;
  });
}

/** Check whether the messages look like a fresh conversation (at most 1 user message, no assistant/tool). */
export function isFreshConversation(
  messages: Array<{ role?: string }>,
): boolean {
  let userCount = 0;
  for (const m of messages) {
    const role = m.role ?? "";
    if (role === "assistant" || role === "tool") return false;
    if (role === "user") userCount++;
    if (userCount > 1) return false;
  }
  return userCount <= 1;
}
