/**
 * 会话解析阶段：从请求头与消息确定会话键与身份。
 * 纯计算；Redis 激活、会话重置等副作用由后续阶段或 handler 处理。
 */
import type { ReqCtx } from "./types.js";
import type { SessionAdapter } from "./types.js";
import { apiKeyToKeyId } from "../opik.js";
import { resolveSessionKey } from "../guard-adapter.js";
import {
  resolveConversationId,
  resolveThreadId as resolveThreadHeader,
  resolveEffectiveConversationId,
  firstUserMessageFingerprint,
} from "../session/session-key.js";
import { resolveOrCreateSessionId } from "../session/auto-session.js";
import {
  extractCodexSessionId,
  extractWorkbuddySessionId,
} from "../session/client-ids.js";

/** 默认适配器：chat/anthropic 的会话键解析（原 handler 行为）。 */
export const DEFAULT_SESSION_ADAPTER: SessionAdapter = {
  extractRawSessionId(c) {
    return resolveConversationId(c);
  },
  userMessages(body) {
    return body.messages;
  },
  fallbackSessionKey(ctx, keyId, lcHeaders) {
    return resolveSessionKey(ctx.config, lcHeaders, ctx.c.req.path, ctx.body, keyId);
  },
  resolveThreadId(c) {
    return resolveThreadHeader(c);
  },
  resolveIdentity(ctx, keyId) {
    const userId =
      ctx.earlyUserId ||
      ctx.c.req.header("x-user-id") ||
      ctx.c.req.header("x-cb-user-id") ||
      ctx.c.req.header("x-tdai-user-token") ||
      "";
    const resolved = ctx.debugForceUserId || userId;
    return {
      keyId: resolved ? resolved : keyId,
      userId: resolved,
      callerUserKey: ctx.apiKey || null,
    };
  },
};

/** Responses 类客户端（codex / workbuddy）取首条用户消息：body.input。 */
function responsesUserMessages(body: Record<string, unknown>): unknown {
  return (body as { input?: unknown }).input;
}

/**
 * Responses 类客户端无显式会话 ID、且自动生成未命中时的兜底键：
 *   keyId : msg-<首问指纹 sha256 前 16> : <UTC 日桶>
 * 同一首问跨请求稳定（不再逐请求 traceId 碎片化、消除孤儿记忆），跨天自动轮换。
 * 提取不到首问指纹时退回 `${keyId}:${traceId}` 临时键（每 keyId 只 warn 一次）。
 */
const warnedNoFingerprint = new Set<string>();
function responsesFallbackSessionKey(ctx: ReqCtx, keyId: string): string | null {
  if (!ctx.traceId) return null;
  const fp = firstUserMessageFingerprint((ctx.body as { input?: unknown }).input);
  if (fp) {
    const dayBucket = Math.floor(Date.now() / 86_400_000);
    return `${keyId}:msg-${fp.slice(0, 16)}:${dayBucket}`;
  }
  if (!warnedNoFingerprint.has(keyId)) {
    warnedNoFingerprint.add(keyId);
    console.warn(
      `[session-fallback] ${keyId}: 提取不到首问指纹，回退临时键 ${keyId}:${ctx.traceId}（仅 warn 一次）`,
    );
  }
  return `${keyId}:${ctx.traceId}`;
}

/** codex 身份直通：keyId 已由 handler 算好（userId || apiKey hash），不改写。 */
function responsesIdentity(ctx: ReqCtx, keyId: string) {
  return {
    keyId: ctx.keyIdOverride ?? keyId,
    userId: ctx.earlyUserId || "",
    callerUserKey: ctx.apiKey || null,
  };
}

/** codex 适配器：显式 session-id 优先；缺失时走 auto 分支（受 autoConversationId 门控）。 */
export const CODEX_SESSION_ADAPTER: SessionAdapter = {
  extractRawSessionId(_c, lcHeaders, body) {
    return extractCodexSessionId(lcHeaders, body);
  },
  userMessages: responsesUserMessages,
  fallbackSessionKey: responsesFallbackSessionKey,
  resolveThreadId: resolveThreadHeader,
  resolveIdentity: responsesIdentity,
};

/** workbuddy 适配器：autoGenerate=false（与 workbuddy 原行为一致，不主动生成 auto ID）。 */
export const WORKBUDDY_SESSION_ADAPTER: SessionAdapter = {
  ...CODEX_SESSION_ADAPTER,
  extractRawSessionId(_c, lcHeaders, body) {
    return extractWorkbuddySessionId(lcHeaders, body);
  },
  autoGenerate: false,
};

export async function sessionStage(
  ctx: ReqCtx,
  adapter: SessionAdapter = DEFAULT_SESSION_ADAPTER,
): Promise<void> {
  const statMeta = { agentSource: ctx.agentSource, spaceId: ctx.earlySpaceId || undefined };
  const lcHeaders: Record<string, string> = {};
  for (const [k, v] of ctx.c.req.raw.headers.entries()) {
    lcHeaders[k.toLowerCase()] = v;
  }

  const keyId = ctx.keyIdOverride ?? (ctx.apiKey ? apiKeyToKeyId(ctx.apiKey) : "unknown");
  const userMessages = adapter.userMessages(ctx.body);
  let conversationId: string | null = null;
  let threadId: string | null = null;
  let autoGenerated = false;
  let reused = false;
  if (adapter === DEFAULT_SESSION_ADAPTER) {
    const r = resolveEffectiveConversationId(
      ctx.c,
      keyId,
      ctx.config,
      firstUserMessageFingerprint(userMessages),
      statMeta,
    );
    conversationId = r.conversationId;
    threadId = r.threadId;
    autoGenerated = r.autoGenerated;
    reused = !!r.reused;
  } else {
    const raw = adapter.extractRawSessionId(ctx.c, lcHeaders, ctx.body);
    if (adapter.autoGenerate === false) {
      threadId = adapter.resolveThreadId(ctx.c);
      conversationId = raw;
      // workbuddy 自己不生成 auto ID；若客户端回传伪造/串用的 auto-* ID，仍要
      // 过一遍签名校验，防止绕过签名把幽灵会话键塞进 store（与 DEFAULT/codex 对齐）。
      if (raw && raw.startsWith("auto-")) {
        const auto = resolveOrCreateSessionId(
          raw,
          keyId,
          undefined,
          firstUserMessageFingerprint(userMessages),
          threadId ?? "",
          statMeta,
        );
        if (auto.rejected) conversationId = null;
      }
    } else {
      const auto = await resolveOrCreateSessionId(
        raw,
        keyId,
        ctx.config.sessionInit?.autoConversationId,
        firstUserMessageFingerprint(userMessages),
        adapter.resolveThreadId(ctx.c) ?? "",
        statMeta,
      );
      conversationId = auto.sessionId || (auto.rejected ? null : raw);
      threadId = adapter.resolveThreadId(ctx.c);
      autoGenerated = auto.autoGenerated;
      reused = !!auto.reused;
    }
  }
  if (autoGenerated) {
    console.log(
      `[session-auto] action=${reused ? "resumed" : "created"} conversationId=${conversationId} keyId=${keyId}`,
    );
  }
  const sessionKey =
    conversationId ?? adapter.fallbackSessionKey(ctx, keyId, lcHeaders);

  const identity = adapter.resolveIdentity(ctx, keyId);
  ctx.keyId = identity.keyId;
  ctx.lcHeaders = lcHeaders;
  ctx.sessionKey = sessionKey;
  ctx.conversationId = conversationId;
  ctx.threadId = threadId;
  ctx.spaceId = ctx.earlySpaceId;
  ctx.userId = identity.userId;
  ctx.callerUserKey = identity.callerUserKey;
}
