import { describe, it, expect, vi } from "vitest";
import { compactMessages } from "../common/context-compaction.js";
import { resolveOrCreateSessionId } from "../session/auto-session.js";
import { resolvePresetIdentity } from "../session/preset.js";
import type { TeamOption } from "../session/types.js";
import { initGrants, getGrants } from "../tdai/grants-fetcher.js";
import { resolveInjectionTuning } from "../injection/tuning.js";
import { stripInjectedBlocks } from "../injection/injectors/tdai-intent-tools-injector.js";
import { auditMemoryAccess } from "../audit.js";

function round(n: number): Array<Record<string, unknown>> {
  const msgs: Array<Record<string, unknown>> = [
    { role: "system", content: "system-keep" },
  ];
  for (let i = 1; i <= n; i++) {
    msgs.push({ role: "user", content: `u${i}` });
    msgs.push({ role: "assistant", content: `a${i}` });
  }
  return msgs;
}

describe("context-compaction", () => {
  it("不压缩：轮数 <= keepRounds 时原样返回", () => {
    const msgs = round(3);
    const r = compactMessages(msgs, 5);
    expect(r.droppedRounds).toBe(0);
    expect(r.messages).toEqual(msgs);
  });

  it("压缩：保留最近 keepRounds 轮 + system，更早轮替换为占位", () => {
    const msgs = round(20);
    const r = compactMessages(msgs, 3);
    expect(r.droppedRounds).toBe(17);
    // system 保留 + 占位 + 最近 3 轮（u18..a20 = 6 条）
    expect(r.messages.length).toBe(1 + 1 + 6);
    expect(r.messages[0]).toEqual({ role: "system", content: "system-keep" });
    expect(String(r.messages[1].content)).toContain("已压缩 17 轮");
    expect(r.messages[r.messages.length - 1].content).toBe("a20");
  });

  it("空输入安全返回", () => {
    const r = compactMessages([], 3);
    expect(r.messages).toEqual([]);
  });
});

describe("auto-session（会话锁生成）", () => {
  it("显式会话 ID 优先，不生成", () => {
    const r = resolveOrCreateSessionId("explicit-1", "usr-x", { enabled: true, ttlMinutes: 30 });
    expect(r.sessionId).toBe("explicit-1");
    expect(r.autoGenerated).toBe(false);
  });

  it("缺失且开启时生成 auto-<keyId>-<uuid> 并续接", () => {
    initGrants(undefined); // 隔离模块状态不影响本用例
    const cfg = { enabled: true, ttlMinutes: 30 };
    const a = resolveOrCreateSessionId(null, "usr-a", cfg);
    expect(a.sessionId).toMatch(/^auto-usr-a-/);
    expect(a.autoGenerated).toBe(true);
    const b = resolveOrCreateSessionId(null, "usr-a", cfg);
    expect(b.sessionId).toBe(a.sessionId); // TTL 内续接同一会话
  });

  it("未开启时不生成", () => {
    const r = resolveOrCreateSessionId(null, "usr-b", { enabled: false });
    expect(r.sessionId).toBe("");
  });
});

describe("grants（读共享授权）", () => {
  it("无 endpoint 时回退静态表", async () => {
    initGrants({ fallback: [{ teamId: "t1", agentId: "a1" }] });
    const g = await getGrants();
    expect(g).toEqual([{ teamId: "t1", agentId: "a1" }]);
  });

  it("endpoint 拉取成功并缓存 TTL", async () => {
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => [{ teamId: "t2", agentId: "a2" }],
    });
    vi.stubGlobal("fetch", fetchMock);
    initGrants({ endpoint: "http://grants", ttlSeconds: 60, fallback: [] });
    const g1 = await getGrants();
    expect(g1).toEqual([{ teamId: "t2", agentId: "a2" }]);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const g2 = await getGrants(); // TTL 内缓存命中
    expect(g2).toEqual([{ teamId: "t2", agentId: "a2" }]);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    vi.unstubAllGlobals();
  });
});

describe("injection tuning 解析", () => {
  it("default + perAgent 合并，perAgent 覆盖", () => {
    const t = resolveInjectionTuning(
      {
        default: { skillTools: true, memoryToolsGuide: "always" },
        perAgent: { codex: { memoryToolsGuide: "on-intent" } },
      },
      "codex",
    );
    expect(t.skillTools).toBe(true);
    expect(t.memoryToolsGuide).toBe("on-intent");
  });

  it("未知客户端只用 default", () => {
    const t = resolveInjectionTuning(
      { default: { profileMemory: false }, perAgent: { codex: { skillTools: false } } },
      "workbuddy",
    );
    expect(t.profileMemory).toBe(false);
    expect(t.skillTools).toBeUndefined();
  });
});

describe("intent query 剥离注入块", () => {
  it("剥离召回/工具模板块，保留用户原文", () => {
    const raw =
      "<tdai_recalled_l1_memories>xxx</tdai_recalled_l1_memories>" +
      "<tdai_memory_tools>yyy</tdai_memory_tools>" +
      "我的名字是什么";
    expect(stripInjectedBlocks(raw)).toBe("我的名字是什么");
  });
});

describe("audit", () => {
  it("fire-and-forget 不抛错", () => {
    expect(() =>
      auditMemoryAccess({
        actorUser: "u",
        actorAgent: "a",
        action: "recall",
        target: "t:agent",
        result: 1,
      }),
    ).not.toThrow();
  });
});

describe("autoConversationId per-key-msg 策略", () => {
  it("同指纹续接同一会话，不同指纹开新窗口", () => {
    const cfg = { enabled: true, ttlMinutes: 30, strategy: "per-key-msg" as const };
    const a1 = resolveOrCreateSessionId(null, "usr-m", cfg, "fp-a");
    const a2 = resolveOrCreateSessionId(null, "usr-m", cfg, "fp-a");
    const b1 = resolveOrCreateSessionId(null, "usr-m", cfg, "fp-b");
    expect(a1.autoGenerated).toBe(true);
    expect(a2.sessionId).toBe(a1.sessionId);
    expect(b1.sessionId).not.toBe(a1.sessionId);
  });

  it("显式 ID 在 per-key-msg 下仍优先", () => {
    const cfg = { enabled: true, strategy: "per-key-msg" as const };
    const r = resolveOrCreateSessionId("explicit-1", "usr-m", cfg, "fp");
    expect(r.sessionId).toBe("explicit-1");
    expect(r.autoGenerated).toBe(false);
  });

  it("per-key（默认）忽略指纹，同一 key 共享会话", () => {
    const cfg = { enabled: true, ttlMinutes: 30, strategy: "per-key" as const };
    const x = resolveOrCreateSessionId(null, "usr-n", cfg, "fp-x");
    const y = resolveOrCreateSessionId(null, "usr-n", cfg, "fp-y");
    expect(x.sessionId).toBe(y.sessionId);
  });
});

describe("resolvePresetIdentity taskMissingPolicy", () => {
  const teams: TeamOption[] = [
    {
      team_id: "team-a",
      team_name: "A",
      agents: [{ agent_id: "agt-1" } as never],
      tasks: [{ task_id: "task-1" } as never],
    },
  ];

  it("skip（默认）：team+agent 无 task → 注册成功，taskId 为空", () => {
    const r = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1" },
      { enabled: true, taskMissingPolicy: "skip" } as never,
    );
    expect(r.canRegister).toBe(true);
    expect(r.taskId).toBeUndefined();
  });

  it("default：缺 task 时使用 defaultTaskId 占位", () => {
    const r = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1" },
      { enabled: true, taskMissingPolicy: "default", defaultTaskId: "default" } as never,
    );
    expect(r.canRegister).toBe(true);
    expect(r.taskId).toBe("default");
  });

  it("reject：缺 task → mismatch，不注册", () => {
    const r = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1" },
      { enabled: true, taskMissingPolicy: "reject" } as never,
    );
    expect(r.canRegister).toBe(false);
    expect(r.hadMismatch).toBe(true);
    expect(r.mismatchReason).toBe("task-required");
  });

  it("无效 task_id → mismatch（非静默忽略）", () => {
    const r = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1", taskId: "task-404" },
      { enabled: true, taskMissingPolicy: "skip" } as never,
    );
    expect(r.canRegister).toBe(false);
    expect(r.hadMismatch).toBe(true);
    expect(r.mismatchReason).toBe("invalid-task");
  });
});
