/**
 * 会话策略验收测试（ACC-1..ACC-6）——把验收标准固化为可执行用例。
 *
 * 说明：这里用纯函数链模拟"请求 → 身份预选 → 会话 ID 解析"的完整决策路径，
 * 不依赖真实上游/内存内核；HTTP 级端到端见 docs/session-policy.md 的验证步骤。
 * 每条验收标准与 docs/session-policy.md 的对照表一一对应。
 */
import { describe, it, expect, beforeEach, afterAll } from "vitest";
import { resolvePresetIdentity } from "../session/preset.js";
import {
  resolveOrCreateSessionId,
  messageFingerprint,
  __setAutoSessionNow,
  __resetAutoSessionForTests,
} from "../session/auto-session.js";
import { firstUserMessageFingerprint } from "../session/session-key.js";
import type { TeamOption } from "../session/types.js";

const teams: TeamOption[] = [
  {
    team_id: "team-a",
    team_name: "A",
    agents: [{ agent_id: "agt-1" } as never],
    tasks: [{ task_id: "task-1" } as never],
  },
];

/** OpenClaw/Hermes 宽松、其余严格（与生产默认一致）。 */
const DEFAULT_CFG = {
  enabled: true,
  taskMissingPolicy: "reject",
  taskMissingPolicyByAgent: { openclaw: "skip", hermes: "skip" },
} as never;

describe("会话策略验收（ACC-1..ACC-6）", () => {
  beforeEach(() => {
    __resetAutoSessionForTests();
    __setAutoSessionNow(() => 1_000_000);
  });
  afterAll(() => {
    __resetAutoSessionForTests();
    __setAutoSessionNow(() => Date.now());
  });

  it("ACC-1: OpenClaw/Hermes 仅配 x-team-id + x-agent-id → 注册成功且能自动建立会话", () => {
    const preset = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1" },
      DEFAULT_CFG,
      "openclaw",
    );
    expect(preset.canRegister).toBe(true);
    // 无 x-conversation-id → 服务端自动生成
    const s = resolveOrCreateSessionId(
      null,
      "key-openclaw",
      { enabled: true, ttlMinutes: 30 },
    );
    expect(s.autoGenerated).toBe(true);
    expect(s.sessionId).toMatch(/^auto-[0-9a-f]{16}-/);
  });

  it("ACC-2: 多轮中后续请求丢失会话 header → 自动关联同一会话（记忆不中断）", () => {
    const cfg = { enabled: true, ttlMinutes: 30, strategy: "per-key-msg" } as const;
    const history = [
      { role: "system", content: "s" },
      { role: "user", content: "帮我修这个 bug" },
    ];
    const fp = firstUserMessageFingerprint(history)!;
    const first = resolveOrCreateSessionId(null, "key-acc2", cfg, fp);
    // 第二轮：完整历史重发（tool call 后续请求），仍不带会话 header
    const second = resolveOrCreateSessionId(null, "key-acc2", cfg, fp);
    expect(second.sessionId).toBe(first.sessionId);
    // per-key 策略下同样续接
    const cfg2 = { enabled: true, ttlMinutes: 30, strategy: "per-key" } as const;
    const p1 = resolveOrCreateSessionId(null, "key-acc2b", cfg2);
    const p2 = resolveOrCreateSessionId(null, "key-acc2b", cfg2);
    expect(p2.sessionId).toBe(p1.sessionId);
  });

  it("ACC-3: 30 分钟超时后新请求 → 新 conversation，不污染旧会话", () => {
    const cfg = { enabled: true, ttlMinutes: 30 };
    const a = resolveOrCreateSessionId(null, "key-acc3", cfg);
    __setAutoSessionNow(() => 1_000_000 + 30 * 60_000 + 1);
    const b = resolveOrCreateSessionId(null, "key-acc3", cfg);
    expect(b.sessionId).not.toBe(a.sessionId);
  });

  it("ACC-4: 旧配置（显式传会话 header）行为不变，始终优先", () => {
    const s = resolveOrCreateSessionId(
      "explicit-conv-1",
      "key-acc4",
      { enabled: true, ttlMinutes: 30 },
    );
    expect(s.sessionId).toBe("explicit-conv-1");
    expect(s.autoGenerated).toBe(false);
  });

  it("ACC-5: 传入无效 x-task-id → 按 mismatch 处理（非静默忽略）", () => {
    const r = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1", taskId: "task-404" },
      DEFAULT_CFG,
      "openclaw",
    );
    expect(r.canRegister).toBe(false);
    expect(r.hadMismatch).toBe(true);
    expect(r.mismatchReason).toBe("invalid-task");
  });

  it("ACC-6: per-agent 策略——openclaw/hermes 宽松，claude-code 严格", () => {
    for (const agent of ["openclaw", "hermes"]) {
      const r = resolvePresetIdentity(
        teams,
        { teamId: "team-a", agentId: "agt-1" },
        DEFAULT_CFG,
        agent,
      );
      expect(r.canRegister).toBe(true);
    }
    const strict = resolvePresetIdentity(
      teams,
      { teamId: "team-a", agentId: "agt-1" },
      DEFAULT_CFG,
      "claude-code",
    );
    expect(strict.canRegister).toBe(false);
    expect(strict.mismatchReason).toBe("task-required");
  });

  it("指纹工具：首条用户消息指纹稳定（供 per-key-msg 多窗口）", () => {
    expect(messageFingerprint("同一个问题")).toBe(
      firstUserMessageFingerprint([
        { role: "user", content: "同一个问题" },
      ])!,
    );
  });
});
