from typing import Any, Dict, List, Optional, Tuple, Union

StringList = Union[List[str], Tuple[str, ...]]

MECHANISM: str
FEEDBACK_SCHEMA: str

class FeedbackRejected(ValueError): ...

class PolicySnapshot:
    def __init__(
        self, version: int = ..., rules: Tuple[Tuple[str, str], ...] = ...
    ) -> None: ...
    @property
    def version(self) -> int: ...
    @property
    def rules(self) -> Tuple[Tuple[str, str], ...]: ...
    @property
    def sha256(self) -> str: ...
    def dump(self) -> str: ...
    @classmethod
    def load(cls, raw: str) -> PolicySnapshot: ...

class FeedbackOptimizer:
    def __init__(
        self,
        *,
        interface_id: str,
        allowed_sources: StringList,
        excluded_literals: StringList,
        policy: Optional[PolicySnapshot] = ...,
        enabled: bool = ...,
    ) -> None: ...
    @property
    def active(self) -> PolicySnapshot: ...
    @property
    def candidate(self) -> Optional[PolicySnapshot]: ...
    @property
    def enabled(self) -> bool: ...
    def prepare(self, batch: Dict[str, Any]) -> Dict[str, Any]: ...
    def generation_request(self, classifier_system: str) -> Dict[str, Any]: ...
    def submit_response(
        self, packet_sha256: str, raw_response: str
    ) -> PolicySnapshot: ...
    def evaluate(self, comparison: Dict[str, Any]) -> Dict[str, Any]: ...
    def cancel(self, reason: str) -> None: ...
    def rollback(self, reason: str) -> PolicySnapshot: ...
    def disable(self) -> PolicySnapshot: ...
    def audit(self) -> Dict[str, Any]: ...
