/**
 * Prompt-cache stability policy for auto-recall injection.
 *
 * ## Why this exists
 *
 * OpenAI-compatible providers (DeepSeek, MiMo, Qwen, GLM, …) implement prompt
 * caching as **automatic prefix matching**: the provider hashes the serialized
 * request from the very first token and reuses the longest identical prefix of
 * a previous request.  There is no explicit breakpoint — OpenClaw's
 * `<!-- OPENCLAW_CACHE_BOUNDARY -->` marker is *stripped* for these providers
 * (see openclaw `openai-transport-stream`: `stripSystemPromptCacheBoundary`),
 * so it only influences Anthropic-style `cache_control` placement.
 *
 * The practical consequence: **the only thing that matters is byte stability of
 * the request prefix**. Two failure modes destroy it:
 *
 *  1. *System-prompt churn.* `appendSystemContext` is concatenated to the tail
 *     of the system prompt (openclaw `composeSystemPromptWithHookContext`).
 *     Persona (L3) and scene navigation (L2) are regenerated by background
 *     pipelines, and the scene index carries a monotonically increasing `heat`
 *     counter.  Every regeneration mutates the tail of the system prompt, which
 *     invalidates *the entire conversation* that follows it — a 100% miss on
 *     that request.
 *
 *  2. *Per-turn user-prompt injection.* `prependContext` is applied through an
 *     ephemeral `transformContext` wrapper that only rewrites the **current**
 *     turn's user message (openclaw `installModelPromptTransform`).  On the next
 *     turn that message reverts to its clean form, so turn N's request and turn
 *     N+1's request diverge at turn N's user message.  Injecting on every turn
 *     therefore guarantees one prefix break per turn.
 *
 * ## What this module does
 *
 *  - `resolveSystemContext()` freezes the "stable" system context per session so
 *    background pipeline writes cannot silently invalidate an in-flight
 *    conversation.  A refresh is only allowed once a minimum number of turns
 *    *and* a minimum wall-clock interval have elapsed, which bounds the number
 *    of full-prefix invalidations per session.
 *
 *  - `filterMemories()` performs session-level de-duplication of recalled L1
 *    memories.  A memory already shown in this session is still in the model's
 *    context window, so re-injecting it buys nothing and costs one prefix break.
 *    When nothing new is recalled the turn injects *no* dynamic context at all,
 *    which keeps the transcript append-only and the prefix intact.
 *
 * All state is in-memory and per-process; losing it degrades to the previous
 * behaviour (re-inject + refresh), never to incorrect output.
 */

import type { Logger } from "../types.js";

const TAG = "[memory-tdai] [cache-policy]";

/** Tunables for prompt-cache stability. Mirrors `recall.cacheStability` config. */
export interface RecallCacheStabilityOptions {
  /** Master switch. When false, every method becomes a pass-through. */
  enabled: boolean;
  /** Freeze `appendSystemContext` for the lifetime of a session. */
  freezeSystemContext: boolean;
  /** Minimum wall-clock interval (ms) before a frozen system context may refresh. */
  systemContextRefreshMs: number;
  /** Minimum number of turns before a frozen system context may refresh. */
  systemContextRefreshTurns: number;
  /** Skip L1 memories that were already injected earlier in the same session. */
  dedupMemories: boolean;
  /** Upper bound on remembered memory ids per session (FIFO eviction). */
  dedupMaxTracked: number;
  /** Drop per-session state after this much inactivity (ms). */
  sessionTtlMs: number;
  /**
   * Render scene navigation with heat *tiers* and a deterministic sort instead
   * of raw counters + mtime, so ordinary usage does not rewrite the block.
   */
  stabilizeSceneNavigation: boolean;
}

export const DEFAULT_CACHE_STABILITY: RecallCacheStabilityOptions = {
  enabled: true,
  freezeSystemContext: true,
  systemContextRefreshMs: 30 * 60 * 1000,
  systemContextRefreshTurns: 20,
  dedupMemories: true,
  dedupMaxTracked: 300,
  sessionTtlMs: 12 * 60 * 60 * 1000,
  stabilizeSceneNavigation: true,
};

/** A recalled memory line together with the identity used for de-duplication. */
export interface RecallItem {
  /** Stable record id from the store; falls back to a content hash when absent. */
  id: string;
  /** Memory type tag (persona / episodic / instruction / …). */
  type: string;
  /** Fully formatted injection line. */
  line: string;
  /** Raw memory content without the type/time decorations (used for metrics). */
  content: string;
}

export interface SystemContextDecision {
  /** The text that should actually be injected (may be an older, frozen revision). */
  text?: string;
  /** True when the frozen revision was replaced by the freshly computed one. */
  refreshed: boolean;
  /** True when a change was detected but deliberately withheld to protect the cache. */
  withheld: boolean;
  /** Human-readable reason, for logs / metrics. */
  reason: string;
}

export interface MemoryFilterDecision {
  kept: RecallItem[];
  /** Ids skipped because they were already injected in this session. */
  skippedIds: string[];
}

interface SessionState {
  /** Frozen system context currently in force. */
  systemContext?: string;
  /** Epoch ms when the frozen revision was installed. */
  frozenAt: number;
  /** Turn index at which the frozen revision was installed. */
  frozenAtTurn: number;
  /** Number of recall turns observed for this session. */
  turns: number;
  /** Ids already injected, in insertion order (FIFO eviction). */
  injectedIds: Set<string>;
  injectedOrder: string[];
  /** Epoch ms of the last interaction, used for GC. */
  lastSeenAt: number;
}

/**
 * Normalize exactly the way OpenClaw does before embedding a hook section into
 * the system prompt (`normalizeStructuredPromptSection`).  Comparing normalized
 * text avoids "refreshing" for pure whitespace churn that the host would have
 * collapsed anyway.
 */
export function normalizeSystemContext(text: string): string {
  return text.replace(/\r\n?/g, "\n").replace(/[ \t]+$/gm, "").trim();
}

/** Cheap, stable 32-bit content hash — only used for logging / fallback ids. */
export function stableHash(text: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

export class RecallCachePolicy {
  private readonly opts: RecallCacheStabilityOptions;
  private readonly logger?: Logger;
  private readonly sessions = new Map<string, SessionState>();

  constructor(opts?: Partial<RecallCacheStabilityOptions>, logger?: Logger) {
    this.opts = { ...DEFAULT_CACHE_STABILITY, ...(opts ?? {}) };
    this.logger = logger;
  }

  get options(): RecallCacheStabilityOptions {
    return this.opts;
  }

  /** Register a new recall turn for this session and return the 1-based turn index. */
  beginTurn(sessionKey: string, now = Date.now()): number {
    const state = this.ensure(sessionKey, now);
    state.turns += 1;
    state.lastSeenAt = now;
    this.sweep(now);
    return state.turns;
  }

  /**
   * Decide which revision of the stable system context to inject.
   *
   * The freshly computed text is only promoted when the session has no frozen
   * revision yet, or when both refresh gates (turns + wall clock) have been
   * passed.  Otherwise the previous revision is replayed byte-for-byte so the
   * provider's prefix cache survives background pipeline writes.
   */
  resolveSystemContext(
    sessionKey: string,
    freshText: string | undefined,
    now = Date.now(),
  ): SystemContextDecision {
    if (!this.opts.enabled || !this.opts.freezeSystemContext) {
      return { text: freshText, refreshed: true, withheld: false, reason: "freeze-disabled" };
    }

    const state = this.ensure(sessionKey, now);
    state.lastSeenAt = now;

    const normalized = freshText ? normalizeSystemContext(freshText) : undefined;

    // Nothing to inject and nothing frozen — nothing to do.
    if (!normalized && !state.systemContext) {
      return { text: undefined, refreshed: false, withheld: false, reason: "empty" };
    }

    // Content disappeared (e.g. persona.md temporarily unreadable). Keep serving
    // the frozen revision: a transient read failure must not bust the cache.
    if (!normalized && state.systemContext) {
      return {
        text: state.systemContext,
        refreshed: false,
        withheld: true,
        reason: "fresh-empty-keep-frozen",
      };
    }

    if (!state.systemContext) {
      state.systemContext = normalized;
      state.frozenAt = now;
      state.frozenAtTurn = state.turns;
      return { text: normalized, refreshed: true, withheld: false, reason: "first-freeze" };
    }

    if (state.systemContext === normalized) {
      return { text: state.systemContext, refreshed: false, withheld: false, reason: "unchanged" };
    }

    const turnsSince = state.turns - state.frozenAtTurn;
    const msSince = now - state.frozenAt;
    const turnGateOpen = turnsSince >= this.opts.systemContextRefreshTurns;
    const timeGateOpen = msSince >= this.opts.systemContextRefreshMs;

    if (turnGateOpen && timeGateOpen) {
      const prevHash = stableHash(state.systemContext);
      state.systemContext = normalized;
      state.frozenAt = now;
      state.frozenAtTurn = state.turns;
      this.logger?.debug?.(
        `${TAG} System context refreshed for ${sessionKey}: ${prevHash} → ${stableHash(normalized!)} ` +
        `(turnsSince=${turnsSince}, msSince=${msSince})`,
      );
      return { text: normalized, refreshed: true, withheld: false, reason: "refresh-gates-open" };
    }

    this.logger?.debug?.(
      `${TAG} System context change withheld for ${sessionKey} to preserve prefix cache ` +
      `(turnsSince=${turnsSince}/${this.opts.systemContextRefreshTurns}, ` +
      `msSince=${msSince}/${this.opts.systemContextRefreshMs})`,
    );
    return {
      text: state.systemContext,
      refreshed: false,
      withheld: true,
      reason: turnGateOpen ? "time-gate-closed" : "turn-gate-closed",
    };
  }

  /**
   * Drop memories that were already injected earlier in this session.
   *
   * Rationale: an injected memory is still present in the model's context, so a
   * repeat injection adds tokens *and* forces a prefix break without adding
   * information.
   *
   * This call is a **pure preview** — it never records anything.  The caller
   * must invoke {@link commitInjected} with the ids that actually survived the
   * character budget, otherwise a memory that was filtered out downstream would
   * be marked as "already shown" and never surface again in this session.
   */
  filterMemories(sessionKey: string, items: RecallItem[], now = Date.now()): MemoryFilterDecision {
    if (!this.opts.enabled || !this.opts.dedupMemories || items.length === 0) {
      return { kept: items, skippedIds: [] };
    }

    const state = this.ensure(sessionKey, now);
    state.lastSeenAt = now;

    const kept: RecallItem[] = [];
    const skippedIds: string[] = [];
    for (const item of items) {
      if (state.injectedIds.has(item.id)) {
        skippedIds.push(item.id);
        continue;
      }
      kept.push(item);
    }

    if (skippedIds.length > 0) {
      this.logger?.debug?.(
        `${TAG} Dedup for ${sessionKey}: ${items.length} recalled → ${kept.length} new ` +
        `(skipped ${skippedIds.length} already-injected)`,
      );
    }

    return { kept, skippedIds };
  }

  /**
   * Record the ids that were really injected into the prompt.
   *
   * Split from {@link filterMemories} on purpose: the recall budget may drop or
   * truncate lines *after* de-duplication, and a request may be abandoned by the
   * recall timeout.  Only the ids that reach the model may be remembered.
   */
  commitInjected(sessionKey: string, ids: string[], now = Date.now()): void {
    if (!this.opts.enabled || !this.opts.dedupMemories || ids.length === 0) return;

    const state = this.ensure(sessionKey, now);
    state.lastSeenAt = now;

    for (const id of ids) {
      if (state.injectedIds.has(id)) continue;
      state.injectedIds.add(id);
      state.injectedOrder.push(id);
    }

    // FIFO eviction so a very long session cannot grow the set without bound.
    const overflow = state.injectedOrder.length - this.opts.dedupMaxTracked;
    if (overflow > 0) {
      const evicted = state.injectedOrder.splice(0, overflow);
      for (const id of evicted) state.injectedIds.delete(id);
    }
  }

  /** True when this session already has a frozen system-context revision. */
  hasFrozenSystemContext(sessionKey: string): boolean {
    return !!this.sessions.get(sessionKey)?.systemContext;
  }

  /** Forget a session (used on explicit reset / compaction). */
  reset(sessionKey: string): void {
    this.sessions.delete(sessionKey);
  }

  /** Number of tracked sessions — exposed for tests and diagnostics. */
  get sessionCount(): number {
    return this.sessions.size;
  }

  private ensure(sessionKey: string, now: number): SessionState {
    let state = this.sessions.get(sessionKey);
    if (!state) {
      state = {
        systemContext: undefined,
        frozenAt: 0,
        frozenAtTurn: 0,
        turns: 0,
        injectedIds: new Set<string>(),
        injectedOrder: [],
        lastSeenAt: now,
      };
      this.sessions.set(sessionKey, state);
    }
    return state;
  }

  private sweep(now: number): void {
    if (this.sessions.size === 0) return;
    const ttl = this.opts.sessionTtlMs;
    for (const [key, state] of this.sessions) {
      if (now - state.lastSeenAt > ttl) this.sessions.delete(key);
    }
  }
}
